export const itemData = [
  {
    "itemType": "Amulets",
    "itemClass": "Amulets",
    "currencySearchName": "Amulet",
    "baseTypes": [
      "Crimson Amulet",
      "Azure Amulet",
      "Amber Amulet",
      "Jade Amulet",
      "Lapis Amulet",
      "Lunar Amulet",
      "Bloodstone Amulet",
      "Stellar Amulet",
      "Solar Amulet",
      "Gold Amulet"
    ]
  },
  {
    "itemType": "Belts",
    "itemClass": "Belts",
    "currencySearchName": "Belt",
    "baseTypes": [
      "Golden Obi",
      "Rawhide Belt",
      "Linen Belt",
      "Wide Belt",
      "Long Belt",
      "Plate Belt",
      "Ornate Belt",
      "Mail Belt",
      "Double Belt",
      "Heavy Belt",
      "Utility Belt",
      "Fine Belt"
    ]
  },
  {
    "itemType": "Body Armours",
    "itemClass": "Body Armours",
    "currencySearchName": "Body Armour",
    "baseTypes": [
      "Golden Mantle",
      "Rusted Cuirass",
      "Fur Plate",
      "Iron Cuirass",
      "Raider Plate",
      "Maraketh Cuirass",
      "Steel Plate",
      "Full Plate",
      "Vaal Cuirass",
      "Juggernaut Plate",
      "Chieftain Cuirass",
      "Colosseum Plate",
      "Champion Cuirass",
      "Glorious Plate",
      "Conqueror Plate",
      "Abyssal Cuirass",
      "Leather Vest",
      "Quilted Vest",
      "Pathfinder Coat",
      "Shrouded Vest",
      "Rhoahide Coat",
      "Studded Vest",
      "Scout's Vest",
      "Serpentscale Coat",
      "Corsair Vest",
      "Smuggler Coat",
      "Strider Vest",
      "Hardleather Coat",
      "Exquisite Vest",
      "Mail Coat",
      "Armoured Vest",
      "Tattered Robe",
      "Feathered Robe",
      "Hexer's Robe",
      "Bone Raiment",
      "Silk Robe",
      "Keth Raiment",
      "Votive Raiment",
      "Altar Robe",
      "Elementalist Robe",
      "Mystic Raiment",
      "Imperial Robe",
      "Plated Raiment",
      "Havoc Raiment",
      "Enlightened Robe",
      "Arcane Robe",
      "Chain Mail",
      "Rogue Armour",
      "Vagabond Armour",
      "Cloaked Mail",
      "Explorer Armour",
      "Scale Mail",
      "Knight Armour",
      "Ancestral Mail",
      "Lamellar Mail",
      "Gladiator Armour",
      "Heroic Armour",
      "Tournament Mail",
      "Slayer Armour",
      "Pilgrim Vestments",
      "Pelt Mantle",
      "Mail Vestments",
      "Shaman Mantle",
      "Ironclad Vestments",
      "Sacrificial Mantle",
      "Cleric Vestments",
      "Tideseer Mantle",
      "Gilded Vestments",
      "Venerated Mantle",
      "Revered Vestments",
      "Corvus Mantle",
      "Zenith Vestments",
      "Hermit Garb",
      "Waxed Jacket",
      "Marabout Garb",
      "Wayfarer Jacket",
      "Anchorite Garb",
      "Scalper's Jacket",
      "Scoundrel Jacket",
      "Ascetic Garb",
      "Clandestine Jacket",
      "Monastic Garb",
      "Torment Jacket",
      "Devout Garb",
      "Assassin Garb",
      "Garment",
      "Grand Regalia",
      "Advanced Fur Plate",
      "Advanced Iron Cuirass",
      "Advanced Maraketh Cuirass",
      "Advanced Steel Plate",
      "Advanced Full Plate",
      "Advanced Vaal Cuirass",
      "Advanced Quilted Vest",
      "Advanced Pathfinder Coat",
      "Advanced Rhoahide Coat",
      "Advanced Studded Vest",
      "Advanced Scout's Vest",
      "Advanced Serpentscale Coat",
      "Advanced Feathered Robe",
      "Advanced Hexer's Robe",
      "Advanced Silk Robe",
      "Advanced Keth Raiment",
      "Advanced Votive Raiment",
      "Advanced Altar Robe",
      "Advanced Chain Mail",
      "Advanced Rogue Armour",
      "Advanced Vagabond Armour",
      "Advanced Cloaked Mail",
      "Advanced Explorer Armour",
      "Advanced Scale Mail",
      "Advanced Pilgrim Vestments",
      "Advanced Pelt Mantle",
      "Advanced Mail Vestments",
      "Advanced Shaman Mantle",
      "Advanced Ironclad Vestments",
      "Advanced Sacrificial Mantle",
      "Advanced Hermit Garb",
      "Advanced Waxed Jacket",
      "Advanced Marabout Garb",
      "Advanced Wayfarer Jacket",
      "Advanced Anchorite Garb",
      "Advanced Scalper's Jacket",
      "Expert Iron Cuirass",
      "Expert Steel Plate",
      "Expert Vaal Cuirass",
      "Expert Pathfinder Coat",
      "Expert Studded Vest",
      "Expert Serpentscale Coat",
      "Expert Hexer's Robe",
      "Expert Keth Raiment",
      "Expert Altar Robe",
      "Expert Rogue Armour",
      "Expert Cloaked Mail",
      "Expert Scale Mail",
      "Expert Pelt Mantle",
      "Expert Shaman Mantle",
      "Expert Sacrificial Mantle",
      "Expert Waxed Jacket",
      "Expert Wayfarer Jacket",
      "Expert Scalper's Jacket"
    ]
  },
  {
    "itemType": "Boots",
    "itemClass": "Boots",
    "currencySearchName": "Boots",
    "baseTypes": [
      "Golden Caligae",
      "Rough Greaves",
      "Iron Greaves",
      "Bronze Greaves",
      "Trimmed Greaves",
      "Stone Greaves",
      "Reefsteel Greaves",
      "Monument Greaves",
      "Totemic Greaves",
      "Rawhide Boots",
      "Laced Boots",
      "Embossed Boots",
      "Steeltoe Boots",
      "Lizardscale Boots",
      "Flared Boots",
      "Leatherplate Boots",
      "Embroidered Boots",
      "Straw Sandals",
      "Wrapped Sandals",
      "Lattice Sandals",
      "Silk Slippers",
      "Feathered Sandals",
      "Flax Sandals",
      "Studded Sandals",
      "Elaborate Sandals",
      "Mail Sabatons",
      "Braced Sabatons",
      "Stacked Sabatons",
      "Covered Sabatons",
      "Flexile Sabatons",
      "Bold Sabatons",
      "Padded Leggings",
      "Secured Leggings",
      "Pelt Leggings",
      "Weaver Leggings",
      "Gilt Leggings",
      "Pious Leggings",
      "Frayed Shoes",
      "Threaded Shoes",
      "Hunting Shoes",
      "Steelpoint Shoes",
      "Velour Shoes",
      "Bladed Shoes",
      "Grand Cuisses",
      "Advanced Iron Greaves",
      "Advanced Bronze Greaves",
      "Advanced Trimmed Greaves",
      "Advanced Stone Greaves",
      "Advanced Laced Boots",
      "Advanced Embossed Boots",
      "Advanced Steeltoe Boots",
      "Advanced Lizardscale Boots",
      "Advanced Wrapped Sandals",
      "Advanced Lattice Sandals",
      "Advanced Silk Slippers",
      "Advanced Feathered Sandals",
      "Advanced Mail Sabatons",
      "Advanced Braced Sabatons",
      "Advanced Stacked Sabatons",
      "Advanced Padded Leggings",
      "Advanced Secured Leggings",
      "Advanced Pelt Leggings",
      "Advanced Frayed Shoes",
      "Advanced Threaded Shoes",
      "Advanced Hunting Shoes",
      "Expert Iron Greaves",
      "Expert Trimmed Greaves",
      "Expert Stone Greaves",
      "Expert Laced Boots",
      "Expert Steeltoe Boots",
      "Expert Lizardscale Boots",
      "Expert Wrapped Sandals",
      "Expert Silk Slippers",
      "Expert Feathered Sandals",
      "Expert Mail Sabatons",
      "Expert Braced Sabatons",
      "Expert Stacked Sabatons",
      "Expert Padded Leggings",
      "Expert Secured Leggings",
      "Expert Pelt Leggings",
      "Expert Frayed Shoes",
      "Expert Threaded Shoes",
      "Expert Hunting Shoes"
    ]
  },
  {
    "itemType": "Bows",
    "itemClass": "Bows",
    "currencySearchName": "Bow",
    "baseTypes": [
      "Crude Bow",
      "Shortbow",
      "Warden Bow",
      "Recurve Bow",
      "Composite Bow",
      "Dualstring Bow",
      "Cultist Bow",
      "Zealot Bow",
      "Artillery Bow",
      "Tribal Bow",
      "Greatbow",
      "Double Limb Bow",
      "Heavy Bow",
      "Advanced Shortbow",
      "Advanced Warden Bow",
      "Advanced Composite Bow",
      "Advanced Dualstring Bow",
      "Advanced Cultist Bow",
      "Advanced Zealot Bow",
      "Expert Shortbow",
      "Expert Composite Bow",
      "Expert Warden Bow",
      "Expert Dualstring Bow",
      "Expert Cultist Bow",
      "Expert Zealot Bow"
    ]
  },
  {
    "itemType": "Catalysts",
    "itemClass": "Stackable Currency",
    "currencySearchName": "Catalyst",
    "baseTypes": [
      "Flesh Catalyst",
      "Neural Catalyst",
      "Carapace Catalyst",
      "Uul-Netol's Catalyst",
      "Xoph's Catalyst",
      "Tul's Catalyst",
      "Esh's Catalyst",
      "Chayula's Catalyst",
      "Reaver Catalyst",
      "Sibilant Catalyst",
      "Skittering Catalyst",
      "Adaptive Catalyst"
    ]
  },
  {
    "itemType": "Charms",
    "itemClass": "Charms",
    "currencySearchName": "Charm",
    "baseTypes": [
      "Thawing Charm",
      "Staunching Charm",
      "Antidote Charm",
      "Dousing Charm",
      "Grounding Charm",
      "Stone Charm",
      "Silver Charm",
      "Ruby Charm",
      "Sapphire Charm",
      "Topaz Charm",
      "Amethyst Charm",
      "Golden Charm"
    ]
  },
  {
    "itemType": "Crossbows",
    "itemClass": "Crossbows",
    "currencySearchName": "Crossbow",
    "baseTypes": [
      "Makeshift Crossbow",
      "Tense Crossbow",
      "Sturdy Crossbow",
      "Varnished Crossbow",
      "Dyad Crossbow",
      "Alloy Crossbow",
      "Bombard Crossbow",
      "Construct Crossbow",
      "Blackfire Crossbow",
      "Piercing Crossbow",
      "Cumbrous Crossbow",
      "Dedalian Crossbow",
      "Esoteric Crossbow",
      "Advanced Tense Crossbow",
      "Advanced Sturdy Crossbow",
      "Advanced Varnished Crossbow",
      "Advanced Dyad Crossbow",
      "Advanced Bombard Crossbow",
      "Advanced Forlorn Crossbow",
      "Expert Sturdy Crossbow",
      "Expert Varnished Crossbow",
      "Expert Tense Crossbow",
      "Expert Dyad Crossbow",
      "Expert Bombard Crossbow",
      "Expert Forlorn Crossbow"
    ]
  },
  {
    "itemType": "Currency",
    "itemClass": "Stackable Currency",
    "currencySearchName": "Stackable Currency",
    "baseTypes": [
      "Blacksmith's Whetstone",
      "Arcanist's Etcher",
      "Scroll of Wisdom",
      "Chaos Orb",
      "Armourer's Scrap",
      "Mirror of Kalandra",
      "Orb of Alchemy",
      "Orb of Chance",
      "Orb of Transmutation",
      "Exalted Orb",
      "Regal Orb",
      "Orb of Augmentation",
      "Glassblower's Bauble",
      "Gemcutter's Prism",
      "Lesser Jeweller's Orb",
      "Greater Jeweller's Orb",
      "Perfect Jeweller's Orb",
      "Artificer's Orb",
      "Divine Orb",
      "Transmutation Shard",
      "Alchemy Shard",
      "Chance Shard",
      "Albino Rhoa Feather",
      "Vaal Orb",
      "Orb of Annulment",
      "Regal Shard",
      "Artificer's Shard",
      "Exotic Coinage",
      "Broken Circle Artifact",
      "Black Scythe Artifact",
      "Order Artifact",
      "Sun Artifact",
      "Gold",
      "Bronze Key",
      "Silver Key",
      "Gold Key"
    ]
  },
  {
    "itemType": "Distilled Emotions",
    "itemClass": "Stackable Currency",
    "currencySearchName": "Distilled",
    "baseTypes": [
      "Distilled Despair",
      "Distilled Disgust",
      "Distilled Envy",
      "Distilled Fear",
      "Distilled Greed",
      "Distilled Guilt",
      "Distilled Ire",
      "Distilled Isolation",
      "Distilled Paranoia",
      "Distilled Suffering"
    ]
  },
  {
    "itemType": "Essences",
    "itemClass": "Stackable Currency",
    "currencySearchName": "Essence",
    "baseTypes": [
      "Essence of the Body",
      "Essence of the Mind",
      "Essence of Enhancement",
      "Essence of Torment",
      "Essence of Flames",
      "Essence of Ice",
      "Essence of Electricity",
      "Essence of Ruin",
      "Essence of Battle",
      "Essence of Sorcery",
      "Essence of Haste",
      "Essence of the Infinite",
      "Greater Essence of the Body",
      "Greater Essence of the Mind",
      "Greater Essence of Enhancement",
      "Greater Essence of Torment",
      "Greater Essence of Flames",
      "Greater Essence of Ice",
      "Greater Essence of Electricity",
      "Greater Essence of Ruin",
      "Greater Essence of Battle",
      "Greater Essence of Sorcery",
      "Greater Essence of Haste",
      "Greater Essence of the Infinite"
    ]
  },
  {
    "itemType": "Foci",
    "itemClass": "Foci",
    "currencySearchName": "Focus",
    "baseTypes": [
      "Twig Focus",
      "Woven Focus",
      "Antler Focus",
      "Engraved Focus",
      "Tonal Focus",
      "Crystal Focus",
      "Voodoo Focus",
      "Plumed Focus",
      "Jade Focus",
      "Paua Focus",
      "Elegant Focus",
      "Attuned Focus",
      "Magus Focus",
      "Advanced Woven Focus",
      "Advanced Antler Focus",
      "Advanced Tonal Focus",
      "Advanced Crystal Focus",
      "Advanced Voodoo Focus",
      "Advanced Plumed Focus",
      "Expert Antler Focus",
      "Expert Crystal Focus",
      "Expert Plumed Focus"
    ]
  },
  {
    "itemType": "Gloves",
    "itemClass": "Gloves",
    "currencySearchName": "Gloves",
    "baseTypes": [
      "Golden Bracers",
      "Stocky Mitts",
      "Riveted Mitts",
      "Tempered Mitts",
      "Bolstered Mitts",
      "Moulded Mitts",
      "Detailed Mitts",
      "Titan Mitts",
      "Grand Mitts",
      "Suede Bracers",
      "Firm Bracers",
      "Bound Bracers",
      "Sectioned Bracers",
      "Spined Bracers",
      "Fine Bracers",
      "Hardened Bracers",
      "Engraved Bracers",
      "Torn Gloves",
      "Sombre Gloves",
      "Stitched Gloves",
      "Jewelled Gloves",
      "Intricate Gloves",
      "Pauascale Gloves",
      "Embroidered Gloves",
      "Adorned Gloves",
      "Ringmail Gauntlets",
      "Layered Gauntlets",
      "Doubled Gauntlets",
      "Plate Gauntlets",
      "Burnished Gauntlets",
      "Ornate Gauntlets",
      "Rope Cuffs",
      "Aged Cuffs",
      "Goldcast Cuffs",
      "Diviner Cuffs",
      "Righteous Cuffs",
      "Signet Cuffs",
      "Gauze Wraps",
      "Linen Wraps",
      "Spiral Wraps",
      "Buckled Wraps",
      "Furtive Wraps",
      "Utility Wraps",
      "Grand Manchettes",
      "Advanced Riveted Mitts",
      "Advanced Tempered Mitts",
      "Advanced Bolstered Mitts",
      "Advanced Moulded Mitts",
      "Advanced Firm Bracers",
      "Advanced Bound Bracers",
      "Advanced Sectioned Bracers",
      "Advanced Spined Bracers",
      "Advanced Sombre Gloves",
      "Advanced Stitched Gloves",
      "Advanced Jewelled Gloves",
      "Advanced Intricate Gloves",
      "Advanced Ringmail Gauntlets",
      "Advanced Layered Gauntlets",
      "Advanced Doubled Gauntlets",
      "Advanced Rope Cuffs",
      "Advanced Aged Cuffs",
      "Advanced Goldcast Cuffs",
      "Advanced Gauze Wraps",
      "Advanced Linen Wraps",
      "Advanced Spiral Wraps",
      "Expert Riveted Mitts",
      "Expert Bolstered Mitts",
      "Expert Moulded Mitts",
      "Expert Firm Bracers",
      "Expert Sectioned Bracers",
      "Expert Spined Bracers",
      "Expert Sombre Gloves",
      "Expert Jewelled Gloves",
      "Expert Intricate Gloves",
      "Expert Ringmail Gauntlets",
      "Expert Layered Gauntlets",
      "Expert Doubled Gauntlets",
      "Expert Rope Cuffs",
      "Expert Aged Cuffs",
      "Expert Goldcast Cuffs",
      "Expert Gauze Wraps",
      "Expert Linen Wraps",
      "Expert Spiral Wraps"
    ]
  },
  {
    "itemType": "Helmets",
    "itemClass": "Helmets",
    "currencySearchName": "Helmet",
    "baseTypes": [
      "Golden Wreath",
      "Golden Visage",
      "Rusted Greathelm",
      "Soldier Greathelm",
      "Wrapped Greathelm",
      "Spired Greathelm",
      "Elite Greathelm",
      "Warrior Greathelm",
      "Commander Greathelm",
      "Fierce Greathelm",
      "Dueling Greathelm",
      "Goliath Greathelm",
      "Guardian Greathelm",
      "Shabby Hood",
      "Felt Cap",
      "Lace Hood",
      "Swathed Cap",
      "Hunter Hood",
      "Viper Cap",
      "Corsair Cap",
      "Leatherbound Hood",
      "Velvet Cap",
      "Covert Hood",
      "Armoured Cap",
      "Twig Circlet",
      "Wicker Tiara",
      "Beaded Circlet",
      "Chain Tiara",
      "Feathered Tiara",
      "Gold Circlet",
      "Coral Circlet",
      "Jade Tiara",
      "Noble Circlet",
      "Twilight Tiara",
      "Magus Tiara",
      "Brimmed Helm",
      "Guarded Helm",
      "Visored Helm",
      "Cowled Helm",
      "Shielded Helm",
      "Closed Helm",
      "Decorated Helm",
      "Gallant Helm",
      "Iron Crown",
      "Horned Crown",
      "Cultist Crown",
      "Martyr Crown",
      "Heavy Crown",
      "Spiritbone Crown",
      "Lavish Crown",
      "Templar Crown",
      "Hewn Mask",
      "Face Mask",
      "Hooded Mask",
      "Veiled Mask",
      "Tribal Mask",
      "Solid Mask",
      "Shaded Mask",
      "Death Mask",
      "Grand Visage",
      "Advanced Rusted Greathelm",
      "Advanced Soldier Greathelm",
      "Advanced Wrapped Greathelm",
      "Advanced Spired Greathelm",
      "Advanced Elite Greathelm",
      "Advanced Shabby Hood",
      "Advanced Felt Cap",
      "Advanced Lace Hood",
      "Advanced Swathed Cap",
      "Advanced Hunter Hood",
      "Advanced Twig Circlet",
      "Advanced Wicker Tiara",
      "Advanced Beaded Circlet",
      "Advanced Chain Tiara",
      "Advanced Feathered Tiara",
      "Advanced Brimmed Helm",
      "Advanced Guarded Helm",
      "Advanced Visored Helm",
      "Advanced Cowled Helm",
      "Advanced Shielded Helm",
      "Advanced Iron Crown",
      "Advanced Horned Crown",
      "Advanced Cultist Crown",
      "Advanced Martyr Crown",
      "Advanced Heavy Crown",
      "Advanced Hewn Mask",
      "Advanced Face Mask",
      "Advanced Hooded Mask",
      "Advanced Veiled Mask",
      "Advanced Tribal Mask",
      "Expert Soldier Greathelm",
      "Expert Spired Greathelm",
      "Expert Elite Greathelm",
      "Expert Felt Cap",
      "Expert Swathed Cap",
      "Expert Hunter Hood",
      "Expert Wicker Tiara",
      "Expert Chain Tiara",
      "Expert Feathered Tiara",
      "Expert Guarded Helm",
      "Expert Cowled Helm",
      "Expert Shielded Helm",
      "Expert Horned Crown",
      "Expert Martyr Crown",
      "Expert Heavy Crown",
      "Expert Face Mask",
      "Expert Veiled Mask",
      "Expert Tribal Mask"
    ]
  },
  {
    "itemType": "Jewels",
    "itemClass": "Jewels",
    "currencySearchName": "Jewel",
    "baseTypes": [
      "Timeless Jewel",
      "Ruby",
      "Emerald",
      "Sapphire",
      "Diamond",
      "Time-Lost Ruby",
      "Time-Lost Emerald",
      "Time-Lost Sapphire",
      "Time-Lost Diamond"
    ]
  },
  {
    "itemType": "Life Flasks",
    "itemClass": "Life Flasks",
    "currencySearchName": "Life Flask",
    "baseTypes": [
      "Lesser Life Flask",
      "Medium Life Flask",
      "Greater Life Flask",
      "Grand Life Flask",
      "Giant Life Flask",
      "Colossal Life Flask",
      "Gargantuan Life Flask",
      "Transcendent Life Flask",
      "Ultimate Life Flask"
    ]
  },
  {
    "itemType": "Mana Flasks",
    "itemClass": "Mana Flasks",
    "currencySearchName": "Mana Flask",
    "baseTypes": [
      "Lesser Mana Flask",
      "Medium Mana Flask",
      "Greater Mana Flask",
      "Grand Mana Flask",
      "Giant Mana Flask",
      "Colossal Mana Flask",
      "Gargantuan Mana Flask",
      "Transcendent Mana Flask",
      "Ultimate Mana Flask"
    ]
  },
  {
    "itemType": "One Hand Maces",
    "itemClass": "One Hand Maces",
    "currencySearchName": "One Hand Mace",
    "baseTypes": [
      "Wooden Club",
      "Smithing Hammer",
      "Slim Mace",
      "Spiked Club",
      "Warpick",
      "Plated Mace",
      "Brigand Mace",
      "Construct Hammer",
      "Morning Star",
      "Jade Club",
      "Lumen Mace",
      "Execratus Hammer",
      "Torment Club",
      "Advanced Smithing Hammer",
      "Advanced Slim Mace",
      "Advanced Warpick",
      "Advanced Plated Mace",
      "Advanced Brigand Mace",
      "Advanced Construct Hammer",
      "Expert Slim Mace",
      "Expert Plated Mace",
      "Expert Smithing Hammer",
      "Expert Warpick",
      "Expert Construct Hammer",
      "Expert Brigand Mace"
    ]
  },
  {
    "itemType": "Quarterstaves",
    "itemClass": "Quarterstaves",
    "currencySearchName": "Quarterstaff",
    "baseTypes": [
      "Wrapped Quarterstaff",
      "Long Quarterstaff",
      "Gothic Quarterstaff",
      "Crackling Quarterstaff",
      "Crescent Quarterstaff",
      "Steelpoint Quarterstaff",
      "Slicing Quarterstaff",
      "Barrier Quarterstaff",
      "Hefty Quarterstaff",
      "Smooth Quarterstaff",
      "Anima Quarterstaff",
      "Graceful Quarterstaff",
      "Wyrm Quarterstaff",
      "Advanced Long Quarterstaff",
      "Advanced Gothic Quarterstaff",
      "Advanced Crackling Quarterstaff",
      "Advanced Crescent Quarterstaff",
      "Advanced Slicing Quarterstaff",
      "Advanced Barrier Quarterstaff",
      "Expert Gothic Quarterstaff",
      "Expert Crescent Quarterstaff",
      "Expert Long Quarterstaff",
      "Expert Crackling Quarterstaff",
      "Expert Barrier Quarterstaff",
      "Expert Slicing Quarterstaff"
    ]
  },
  {
    "itemType": "Quivers",
    "itemClass": "Quivers",
    "currencySearchName": "Quiver",
    "baseTypes": [
      "Broadhead Quiver",
      "Fire Quiver",
      "Sacral Quiver",
      "Two-Point Quiver",
      "Blunt Quiver",
      "Toxic Quiver",
      "Serrated Quiver",
      "Primed Quiver",
      "Penetrating Quiver",
      "Volant Quiver",
      "Visceral Quiver"
    ]
  },
  {
    "itemType": "Relics",
    "itemClass": "Relics",
    "currencySearchName": "Relic",
    "baseTypes": [
      "Urn Relic",
      "Amphora Relic",
      "Vase Relic",
      "Seal Relic",
      "Coffer Relic",
      "Tapestry Relic",
      "Incense Relic"
    ]
  },
  {
    "itemType": "Rings",
    "itemClass": "Rings",
    "currencySearchName": "Ring",
    "baseTypes": [
      "Iron Ring",
      "Lazuli Ring",
      "Ruby Ring",
      "Sapphire Ring",
      "Topaz Ring",
      "Amethyst Ring",
      "Emerald Ring",
      "Pearl Ring",
      "Prismatic Ring",
      "Gold Ring",
      "Unset Ring",
      "Ring",
      "Breach Ring"
    ]
  },
  {
    "itemType": "Sceptres",
    "itemClass": "Sceptres",
    "currencySearchName": "Sceptre",
    "baseTypes": [
      "Rattling Sceptre",
      "Stoic Sceptre",
      "Lupine Sceptre",
      "Omen Sceptre",
      "Ochre Sceptre",
      "Shrine Sceptre",
      "Devouring Sceptre",
      "Clasped Sceptre",
      "Devotional Sceptre",
      "Wrath Sceptre",
      "Aromatic Sceptre",
      "Pious Sceptre",
      "Hallowed Sceptre"
    ]
  },
  {
    "itemType": "Shields",
    "itemClass": "Shields",
    "currencySearchName": "Shield",
    "baseTypes": [
      "Golden Flame",
      "Splintered Tower Shield",
      "Painted Tower Shield",
      "Braced Tower Shield",
      "Barricade Tower Shield",
      "Effigial Tower Shield",
      "Rampart Tower Shield",
      "Heraldric Tower Shield",
      "Stone Tower Shield",
      "Crucible Tower Shield",
      "Ancestor Tower Shield",
      "Phalanx Tower Shield",
      "Defiant Tower Shield",
      "Blacksteel Tower Shield",
      "Hardwood Targe",
      "Pelage Targe",
      "Studded Targe",
      "Crescent Targe",
      "Chiseled Targe",
      "Feathered Targe",
      "Stratified Targe",
      "Carved Targe",
      "Mosaic Targe",
      "Aureate Targe",
      "Grand Targe",
      "Blazon Crest Shield",
      "Sigil Crest Shield",
      "Emblem Crest Shield",
      "Jingling Crest Shield",
      "Sectarian Crest Shield",
      "Omen Crest Shield",
      "Wayward Crest Shield",
      "Seer Crest Shield",
      "Stoic Crest Shield",
      "Empyreal Crest Shield",
      "Deified Crest Shield",
      "Leather Buckler",
      "Wooden Buckler",
      "Plated Buckler",
      "Iron Buckler",
      "Ridged Buckler",
      "Spiked Buckler",
      "Ringed Buckler",
      "Edged Buckler",
      "Laminate Buckler",
      "Pearl Buckler",
      "Ornate Buckler",
      "Array Buckler",
      "Aegis Buckler",
      "Advanced Painted Tower Shield",
      "Advanced Braced Tower Shield",
      "Advanced Effigial Tower Shield",
      "Advanced Rampart Tower Shield",
      "Advanced Heraldric Tower Shield",
      "Advanced Stone Tower Shield",
      "Advanced Hardwood Targe",
      "Advanced Pelage Targe",
      "Advanced Studded Targe",
      "Advanced Crescent Targe",
      "Advanced Chiseled Targe",
      "Advanced Feathered Targe",
      "Advanced Blazon Crest Shield",
      "Advanced Sigil Crest Shield",
      "Advanced Emblem Crest Shield",
      "Advanced Jingling Crest Shield",
      "Advanced Sectarian Crest Shield",
      "Advanced Omen Crest Shield",
      "Advanced Wooden Buckler",
      "Advanced Plated Buckler",
      "Advanced Ridged Buckler",
      "Advanced Spiked Buckler",
      "Advanced Ringed Buckler",
      "Advanced Edged Buckler",
      "Expert Braced Tower Shield",
      "Expert Rampart Tower Shield",
      "Expert Stone Tower Shield",
      "Expert Pelage Targe",
      "Expert Crescent Targe",
      "Expert Feathered Targe",
      "Expert Sigil Crest Shield",
      "Expert Jingling Crest Shield",
      "Expert Omen Crest Shield",
      "Expert Plated Buckler",
      "Expert Spiked Buckler",
      "Expert Edged Buckler"
    ]
  },
  {
    "itemType": "Socketable",
    "itemClass": "Socketable",
    "currencySearchName": "Socketable",
    "baseTypes": [
      "Desert Rune",
      "Glacial Rune",
      "Storm Rune",
      "Iron Rune",
      "Body Rune",
      "Mind Rune",
      "Rebirth Rune",
      "Inspiration Rune",
      "Stone Rune",
      "Vision Rune",
      "Soul Core of Tacati",
      "Soul Core of Opiloti",
      "Soul Core of Jiquani",
      "Soul Core of Zalatl",
      "Soul Core of Citaqualotl",
      "Soul Core of Puhuarte",
      "Soul Core of Tzamoto",
      "Soul Core of Xopec",
      "Soul Core of Azcapa",
      "Soul Core of Topotante",
      "Soul Core of Quipolatl",
      "Soul Core of Ticaba",
      "Soul Core of Atmohua",
      "Soul Core of Cholotl",
      "Soul Core of Zantipi"
    ]
  },
  {
    "itemType": "Splinters",
    "itemClass": "Stackable Currency",
    "currencySearchName": "Splinter",
    "baseTypes": [
      "Breach Splinter",
      "Simulacrum Splinter"
    ]
  },
  {
    "itemType": "Staves",
    "itemClass": "Staves",
    "currencySearchName": "Staff",
    "baseTypes": [
      "Ashen Staff",
      "Gelid Staff",
      "Voltaic Staff",
      "Spriggan Staff",
      "Pyrophyte Staff",
      "Chiming Staff",
      "Rending Staff",
      "Reaping Staff",
      "Icicle Staff",
      "Roaring Staff",
      "Paralysing Staff",
      "Cleric Staff",
      "Dark Staff"
    ]
  },
  {
    "itemType": "Two Hand Maces",
    "itemClass": "Two Hand Maces",
    "currencySearchName": "Two Hand Mace",
    "baseTypes": [
      "Felled Greatclub",
      "Oak Greathammer",
      "Forge Maul",
      "Studded Greatclub",
      "Cultist Greathammer",
      "Temple Maul",
      "Leaden Greathammer",
      "Crumbling Maul",
      "Pointed Maul",
      "Totemic Greatclub",
      "Greatmace",
      "Precise Greathammer",
      "Giant Maul",
      "Advanced Oak Greathammer",
      "Advanced Forge Maul",
      "Advanced Cultist Greathammer",
      "Advanced Temple Maul",
      "Advanced Leaden Greathammer",
      "Advanced Crumbling Maul",
      "Expert Forge Maul",
      "Expert Temple Maul",
      "Expert Oak Greathammer",
      "Expert Cultist Greathammer",
      "Expert Crumbling Maul",
      "Expert Leaden Greathammer"
    ]
  },
  {
    "itemType": "Wands",
    "itemClass": "Wands",
    "currencySearchName": "Wand",
    "baseTypes": [
      "Withered Wand",
      "Bone Wand",
      "Attuned Wand",
      "Siphoning Wand",
      "Volatile Wand",
      "Galvanic Wand",
      "Acrid Wand",
      "Offering Wand",
      "Frigid Wand",
      "Torture Wand",
      "Critical Wand",
      "Primordial Wand",
      "Dueling Wand"
    ]
  },
  {
    "itemType": "Waystones",
    "itemClass": "Waystones",
    "currencySearchName": "Waystone",
    "baseTypes": [
      "Waystone (Tier 1)",
      "Waystone (Tier 2)",
      "Waystone (Tier 3)",
      "Waystone (Tier 4)",
      "Waystone (Tier 5)",
      "Waystone (Tier 6)",
      "Waystone (Tier 7)",
      "Waystone (Tier 8)",
      "Waystone (Tier 9)",
      "Waystone (Tier 10)",
      "Waystone (Tier 11)",
      "Waystone (Tier 12)",
      "Waystone (Tier 13)",
      "Waystone (Tier 14)",
      "Waystone (Tier 15)",
      "Waystone (Tier 16)"
    ]
  }
];
